### PR TITLE
Detect unsupported cctk modes, and act accordingly

### PR DESCRIPTION
**Pull request by alexVinarskis**
Solves https://github.com/alexVinarskis/dell-powermanager/issues/22
- [x] Update data structures to use 'supported' field
- [x] Detect modes support. Safe skip unsupported
- [x] Gray out unsupported mode, with user message
- [x] Detect non-Dell machines, clearly indicate the error
- [ ] Above changes negatively affected start up time: 7-10seconds (used to be ~3seconds). Needs to be resolved before merge

Testing
- [x] Test on Linux (Dell with all modes supported, dell with no modes supported, unsupported platform/lenovo)
- [x] Test on Windows (Dell with all modes supported, dell with no modes supported, unsupported platform/lenovo)
- [x]  Test on @Scridgeon device

### CODE REVIEW

**Comment by alexVinarskis** [comment]
@Scridgeon please give this one a try. This should ignore all unsupported modes, and allow you to use the supported ones. You can get compiled .deb by pressing:

"Show all checks -> Details -> (top left corner) Summary", and selecting .deb file

**Comment by alexVinarskis** [comment]
(fixed regression on windows)

**Comment by alexVinarskis** [comment]
(rebased on top of master)

**Comment by Scridgeon** [comment]
Version 0.8.0-22-g0a359d0+20231228-220258 works great. The scanning completes and all of the fields that are supported on my machine work as expected. I even launched the app via the terminal to watch the output and it kept refreshing the batter info, there were no errors. Thank you for getting this fix implemented.

**Comment by alexVinarskis** [comment]
(fixed bugs found during complete linux/windows testing, squashed commits for merge)

**Pull request merged**
