### PR TITLE
linux: Support non-Debian distros

### PR DESCRIPTION
**Pull request by alexVinarskis**
Initial support of non-debian based linux distros, in this case Arch. Shall resolve [this](https://github.com/alexVinarskis/dell-powermanager/issues/15) issue

Todo:
- [x] Support running `cctk` from `$PATH`
- [x] Support requesting elevation/sudo for `cctk`/run app as sudo/add dynamic `sudoers.d` injection?
- [x] Remove 'Download and Install' dependencies button for non-debian, guide instead
- [x] Remove 'Download and Install' OTA button for non-debian, guide instead

Testing:
- [x] Ubuntu
- [x] Arch
- [x] Windows (new no admin rights menu warning)

### CODE REVIEW

**Comment by josbeir** [comment]
How are you handling elevated permissions in your ubuntu variant? The cctk app always need elevated no ?
Imo this is not a real "arch only" fix, it should apply for all linux distro's where /usr/bin/cctk is present?

**Comment by alexVinarskis** [comment]
On ubuntu cctk is installed to different, predefined path from dell's .deb. During apps Installation, that path is added to `sudoers.d`, which allows any user to - execute the command specified (cctk) as root, without requiring elevation. Strictly speaking, this is a security violation, iff path is user accessible (could modify binary without elevation, and execute malicious commands as root). If path is only modifyable by root (eg. `/usr/bin`), it is okay.

Same trick _could_ be done with any path, but unless the install path is pre-defined, it will have to be added post installation, with one time elevation request. This is probably the approach i will take. Currently on holidays, didn't manage to complete it before 🙈 

Another approach is to run whole app as root, thus requiring elevation on every opening. This is what is done on windows, since it has no sudoers alternative, however:
1. Typing password every time to see power mode is arguably annoying
2. Flutter app behaves weirdly when run as root; dark/light mode does not follow system setting, but is always dark. On wayland with fractional scaling, app becomes blurry (as if its electron app, but it is not), even though it works out of the box on default user.

Compromise between sudoers and app as root would be to run app without elevation, and acquire elevated shell at opening. However, at least in current setup, it is not possible to "keep" elevated shell after the initial command was executed. Perhaps its possible, but i would need to do more research.

**Comment by josbeir** [comment]
> On ubuntu cctk is installed to different, predefined path from dell's .deb. During apps Installation, that path is added to `sudoers.d`, ([this template](https://github.com/alexVinarskis/dell-powermanager/blob/master/resources/sudoers) deployed [here](https://github.com/alexVinarskis/dell-powermanager/blob/master/package.sh#L37)) which allows any user to - execute the command specified (cctk) as root, without requiring elevation. Strictly speaking, this is a security violation, iff path is user accessible (could modify binary without elevation, and execute malicious commands as root). If path is only modifyable by root (eg. `/usr/bin`), it is okay.
> 
> Same trick _could_ be done with any path, but unless the install path is pre-defined, it will have to be added post installation, with one time elevation request. This is probably the approach i will take. Currently on holidays, didn't manage to complete it before 🙈
> 
> Another approach is to run whole app as root, thus requiring elevation on every opening. This is what is done on windows, since it has no sudoers alternative, however:
> 
>     1. Typing password every time to see power mode is arguably annoying
> 
>     2. Flutter app behaves weirdly when run as root; dark/light mode does not follow system setting, but is always dark. On wayland with fractional scaling, app becomes blurry (as if its electron app, but it is not), even though it works out of the box on default user.
Hmm not a fan of that either, as this is a userland app. 

> 
> 
> Compromise between sudoers and app as root would be to run app without elevation, and acquire elevated shell at opening. However, at least in current setup, it is not possible to "keep" elevated shell after the initial command was executed. Perhaps its possible, but i would need to do more research.

Why not ask for password using polkit when needed, eg when changing settings.. ?

$ pkexec <command> or maybe there's a dart lib to handle this?

**Comment by alexVinarskis** [comment]
> Why not ask for password using polkit when needed, eg when changing settings.. ?
> $ pkexec <command>

Yes that's exactly the plan - prompt the user to update the sudoers manually, or offer to call `pkexec` to do it automatically. A similar approach is already used for installation (on ubuntu only).

**Comment by alexVinarskis** [comment]
@josbeir These should make app more linux-generic. Still not packaged for Arch, but I believe you should be able to run it from source without issues now. Let me know how it goes!

**Comment by alexVinarskis** [comment]
> @josbeir These should make app more linux-generic. Still not packaged for Arch, but I believe you should be able to run it from source without issues now. Let me know how it goes!

Just run test on Arch, still has issues, WIP

**Comment by alexVinarskis** [comment]
Successfully tested on EndeavourOS Galileo (Arch based)

**Pull request merged**
